add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$fill\
$battery\
$golang\
$java\
$lua\
$nodejs\
$python\
$rust\
$cmd_duration\
$time\
$character"""

[fill]
symbol = ' '

[character]
success_symbol = '[](bold blue)'
error_symbol = '[✖](bold red)'
format = "\n   $symbol "

[battery]
format = '\[[$symbol$percentage]($style)\]'

[[battery.display]]
threshold = 20
style = 'bold red'
discharging_symbol = ''

[cmd_duration]
style = 'bold cyan'
format = '\[[$duration]($style)\]'

[directory]
style = 'bold blue'
repo_root_style = 'bold blue'
format = '[ ](blue)[ $path ]($style)'
repo_root_format = '[ ](blue)[ $repo_root]($repo_root_style)[$path ]($style)'

[git_branch]
symbol = ''
style = 'bold cyan'
format = '[\[[$symbol $branch]($style)\]]($style)'

[git_status]
style = 'bold cyan'
untracked = ' [](bold yellow)'
ahead = ' ${count}'
diverged = ' ${ahead_count}${behind_count}'
behind = ' ${count}'
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = ''
style    = 'bold blue'
format = '[\[$symbol($version)\]]($style)'

[java]
symbol = ''
style = 'bold #D08770'
format = '[\[$symbol($version)\]]($style)'

[lua]
symbol = ''
style = 'bold blue'
format = '[\[$symbol($version)\]]($style)'

[nodejs]
symbol = ''
style = 'bold green'
format = '[\[$symbol($version)\]]($style)'

[python]
symbol = ''
style = 'bold yellow'
format = '[\[$symbol($version)\]]($style)'

[rust]
symbol = ''
style = 'bold purple'
format = '[\[$symbol($version)\]]($style)'

[time]
disabled = false
style = 'bold white'
format = '\[[$time]($style)\]'
