# ROSE PINE
format = """
$username \
$directory \
$git_branch \
$git_status \
$fill \
$c \
$elixir \
$elm \
$golang \
$haskell \
$java \
$julia \
$nodejs \
$nim \
$rust \
$scala \
$python\n  \
$time\n  \
[󱞪](fg:iris) 
"""

command_timeout = 5000

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay)"
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay)"
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
style = "bg:overlay fg:love"
disabled = false
untracked = ' [ ](bold bg:overlay fg:gold)'
ahead = '  ${count}'
diverged = ' 󰘬  ${ahead_count}${behind_count}'
behind = '  ${count}'
format = '[](fg:overlay)[$all_status$ahead_behind]($style)[](fg:overlay)'

[time]
disabled = false
format = "[](fg:overlay)[ $time  ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
# time_format = "%I:%M"
# use_12hr = false

[username]
disabled = false
format = "[](fg:overlay)[  $user ]($style)[](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

# Languages

[c]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ""

[scala]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = ' '


# CUSTOM
#
# "$schema" = "https://starship.rs/config-schema.json"
#
# add_newline = true
#
# format = """
# $username$directory$git_branch$git_status$time$character
#  (bold blue) """
#
# command_timeout = 5000
#
# [fill]
# symbol = ' '
#
# [character]
# success_symbol = '[](bold yellow)'
# error_symbol = '[](bold red)'
# format = " $symbol "
#
# [username]
# style_root = "bold purple"
# style_user = "bold purple"
# show_always = true
# format = "[$user]($style) in"
#
# [os]
# symbols = { Windows = "  "}
# style = "bold blue"
# disabled = false
#
# [directory]
# style = 'bold blue'
# repo_root_style = 'bold blue'
# format = '[ ](blue)[ $path ]($style)'
# repo_root_format = '[ ](blue)[ $repo_root]($repo_root_style)[$path ]($style)'
#
# [git_branch]
# symbol = ''
# style = 'bold cyan'
# format = '[\[[$symbol $branch]($style)\]]($style)'
#
# [git_status]
# style = 'bold cyan'
# untracked = ' [](bold yellow)'
# ahead = ' ${count}'
# diverged = ' 󰘬${ahead_count}${behind_count}'
# behind = ' ${count}'
# format = '([\[$all_status$ahead_behind\]]($style)) '
#
# [golang]
# symbol = ''
# style    = 'bold blue'
# format = '[\[$symbol($version)\]]($style)'
#
# [lua]
# symbol = ''
# style = 'bold blue'
# format = '[\[$symbol($version)\]]($style)'
#
# [nodejs]
# symbol = ' '
# style = 'bold green'
# format = '[\[$symbol($version)\]]($style)'
#
# [time]
# disabled = false
# style = 'bold purple'
# format = 'at 󰥔 [$time]($style)'
