"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $time$username$directory$git_branch$git_status $fill $c$golang$nodejs$nim$rust$python
# [󱞪](fg:red)
# """


format = """
$time\
$username\
$directory\
$git_branch\
$nodejs\
$character
"""

add_newline = false
command_timeout = 5000

palette = "onedark"

[palettes.onedark]
overlay = '#141724'
red = '#e06c75'
red_darker = '#7d1921'
yellow = '#e5c07b'
blue = '#61afef'

[time]
disabled = false
format = "[█](fg:red)[$time ]($style)[](fg:red_darker bg:red)"
style = "bg:red fg:overlay"

[username]
disabled = false
format = "(fg:red)[  $user ]($style)[](fg:red)"
show_always = true
style_root = "bg:red fg:overlay"
style_user = "bg:red fg:overlay"

[directory]
format = "[](fg:red)[ $path ]($style)[](fg:red)"
style = "bg:red fg:overlay"

[fill]
style = "fg:red"
symbol = " "

[git_branch]
format = "[](fg:red)[ $symbol $branch ]($style)[](fg:red)"
style = "bg:red fg:overlay"
symbol = ""

[git_status]
style = "bg:red fg:overlay"
up_to_date = ""
untracked = '[  ](bold bg:red fg:overlay)'
ahead = '  ${count}(bold bg:red fg:overlay)'
behind = '  ${count}(bold bg:redfg:overlay)'
format = '[](fg:red)[$all_status$ahead_behind]($style)[](fg:red)'

# Languages

# [c]
# style = "bg:red fg:overlay"
# format = "[](fg:red)[$symbol$version]($style)[](fg:red) "
# disabled = false
# symbol = " "
#
# [golang]
# style = "bg:red fg:overlay"
# format = "[](fg:red)[$symbol$version]($style)[](fg:red) "
# disabled = false
# symbol = " "
#
# [nodejs]
# style = "bg:red fg:overlay"
# format = "[](fg:red)[$symbol$version]($style)[](fg:red) "
# disabled = false
# symbol = "󰎙 "
#
# [rust]
# style = "bg:red fg:overlay"
# format = "[](fg:red)[$symbol$version]($style)[](fg:red) "
# disabled = false
# symbol = ""
#
# [python]
# style = "bg:red fg:overlay"
# format = "[](fg:red)[$symbol$version]($style)[](fg:red) "
# disabled = false
# symbol = ' '
