"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

format = """
$username$directory$git_branch$git_status$time$character
 (bold blue) """

command_timeout = 5000

[fill]
symbol = ' '

[character]
success_symbol = '[](bold yellow)'
error_symbol = '[](bold red)'
format = " $symbol "

[username]
style_root = "bold purple"
style_user = "bold purple"
show_always = true
format = "[$user]($style) in"

[os]
symbols = { Windows = "  "}
style = "bold blue"
disabled = false

[directory]
style = 'bold blue'
repo_root_style = 'bold blue'
format = '[ ](blue)[ $path ]($style)'
repo_root_format = '[ ](blue)[ $repo_root]($repo_root_style)[$path ]($style)'

[git_branch]
symbol = ''
style = 'bold cyan'
format = '[\[[$symbol $branch]($style)\]]($style)'

[git_status]
style = 'bold cyan'
untracked = ' [](bold yellow)'
ahead = ' ${count}'
diverged = ' 󰘬${ahead_count}${behind_count}'
behind = ' ${count}'
format = '([\[$all_status$ahead_behind\]]($style)) '

[golang]
symbol = ''
style    = 'bold blue'
format = '[\[$symbol($version)\]]($style)'

[lua]
symbol = ''
style = 'bold blue'
format = '[\[$symbol($version)\]]($style)'

[nodejs]
symbol = ' '
style = 'bold green'
format = '[\[$symbol($version)\]]($style)'

[time]
disabled = false
style = 'bold purple'
format = 'at 󰥔 [$time]($style)'
