"$schema" = 'https://starship.rs/config-schema.json'

format = """
[┌─](bold red)$time$username$directory$c$golang$nodejs$nim$rust$python $fill $git_status$git_branch
[└─](bold red)
"""

add_newline = false
command_timeout = 5000

palette = "onedark"

[palettes.onedark]
overlay = '#141724'
red = '#e06c75'
red_2 = "#cc5d68"
red_3 = "#b84f5a"
red_4 = "#a4424d"

# Left Prompt
[time]
disabled = false
format = "[ $time  ]($style)[](fg:red bg:red_2)"
style = "bg:red fg:overlay"

[username]
disabled = false
format = "[  $user ]($style)[](fg:red_2 bg:red_3)"
show_always = true
style_user = "bg:red_2 fg:overlay"

[directory]
format = "[ $path ]($style)"
style = "bg:red_3 fg:overlay"

[fill]
style = "fg:overlay"
symbol = " "

# Right Prompt

[git_status]
format = '[ $all_status $ahead_behind ]($style)'
up_to_date = "[󰞑](bg:red_2 fg:overlay)"
stashed = "[󰋻](bg:red_2 fg:overlay)"
modified = '[](bg:red_2 fg:overlay)'
ahead = '  ${count}(bg:red_2 fg:overlay)'
behind = '  ${count}(bg:red_2 fg:overlay)'
style = "bg:red_2 fg:overlay"

[git_branch]
format = "[](fg:red bg:red_2)[ $symbol $branch ]($style)"
style = "bg:red fg:overlay"
symbol = ""

# Languages

[c]
format = "[$symbol$version ]($style)"
style = "bg:red_3 fg:overlay"
disabled = false
symbol = " "

[golang]
format = "[$symbol$version ]($style)"
style = "bg:red_3 fg:overlay"
disabled = false
symbol = " "

[nodejs]
format = "[$symbol$version ]($style)"
style = "bg:red_3 fg:overlay"
disabled = false
symbol = "󰎙 "

[rust]
format = "[$symbol$version ]($style)"
style = "bg:red_3 fg:overlay"
disabled = false
symbol = " "

[python]
format = "[$symbol$version ]($style)"
style = "bg:red_3 fg:overlay"
disabled = false
symbol = ' '
